---
title: "rcontroll: an R interface to the individual-based forest growth simulator TROLL"
output: 
  bookdown::html_document2:
    number_sections: false  
    toc: true
    toc_float: yes
  bookdown::word_document2:
    reference_docx: ./template/template.docx
  bookdown::pdf_document2:
    includes:
      before_body: ./template/doc_prefix.tex
      in_header: ./template/preamble.tex
    number_sections: false
    toc: false
    keep_tex: no
linestretch: 1.5
csl: bibliography/mee.csl
bibliography: bibliography/library.bib
link-citations: yes
---

Sylvain Schmitt$^1$, 
Guillaume Salzet$^{2,3}$,
Fabian Jörg Fischer$^{4}$,
Isabelle Maréchaux$^{5}$,
Jerome Chave$^{6}$

*$^1$ CNRS, UMR EcoFoG (Agroparistech, Cirad, INRAE, Université des Antilles, Université de la Guyane), Campus Agronomique, 97310 Kourou, French Guiana;* 
*$^2$ INRAE, UMR BETA, 54042 Nancy, France;*
*$^3$ INRAE, UMR EcoFoG (Agroparistech, Cirad, CNRS, Université des Antilles, Université de la Guyane), Campus Agronomique, 97310 Kourou, French Guiana;*
*$^4$ School of Biological Sciences, University of Bristol, 24 Tyndall Avenue, Bristol, BS8 1TQ, UK;*
*$^5$ AMAP, INRA, Univ Montpellier, IRD, CIRAD, CNRS, F-34000 Montpellier, France;*
*$^6$ Laboratoire Evolution et Diversité Biologique, UMR5174, CNRS, Université Paul Sabatier, IRD, Toulouse Cedex 9, France;*

Correspondence: Sylvain Schmitt, UMR EcoFoG, Campus Agronomique, 97310 Kourou, 
French Guiana. Email: sylvain.m.schmitt@gmail.com

**Running title**: The R interface to the forest simulator TROLL

**Keywords:** word 1 | word 2 | ...

\newpage

# Abstract

<!-- 204/350 words -->

1. Forest dynamics models are of primary importance for predicting the future of complex ecosystems such as tropical forests. Among them, TROLL is an individual-based, spatially explicit forest growth simulator that leverages knowledge of tree ecophysiology to simulate mechanistic tree processes based on functional traits. The TROLL model has been used, among others, to jointly simulate carbon and tree diversity in the Amazon, to explore forest resilience to disturbance, and to improve plant allometries in association with remote sensing. Nevertheless, the necessary but complex C++ code behind the simulator has been a barrier to the widespread use of TROLL in research and education, until now.
1. Here, we present the R package rcontroll, which integrates the individual-based TROLL model to simulate forest ecosystem and species dynamics forward in time. rcontroll provides user-friendly functions to set up and analyse simulations with varying community compositions, ecological parameters, and climate conditions.
1. We show the flexible functionality of the R package rcontroll by demonstrating its use for model calibration, showing its synergy with other R packages, and including reproducible code examples for published studies using TROLL.
1. We developed rcontroll, an easy-to-use R package to open up the TROLL forest simulator to a wider community of ecologists and students using R.


# Introduction

1. The importance of forest dynamics predictions
1. Limits of current tools 
    * especially in tropical forests with outstanding diversity
1. Ensemble of current forest models 
1. Zhan, Donald, & De Angelis 2020
    * Bonan & Gordon 2019
1. Importance of  individual-based and spatially-explicit models
1. introducing TROLL
1. Example of TROLL usage
    * study of spatial patterns [@Chave1999]
    * joint simulation of carbon and tree diversity [@Marechaux2017]
    * explore forest resilience to disturbance [@Schmitt2019]
    * improve plant allometries in association with remote sensing [@Fischer2019]
    * calibration across tropics [@Rau2022]
1. Limits of current TROLL implementation
    * necessary but complex C++ code
1. What we have done: rcontroll

# Materials and methods

## TROLL model

Simple but complete description of the model similar to @Rau2022, maybe focusing on the limit of the current implementation of TROLL. To be discussed with Jérôme, Isabelle & Fabian.

**Add here the Figure 1 that shows TROLL workflow.**

## rcontroll workflow and usage

The TROLL simulator relies on a complex system of equations coded in C++ to efficiently simulate hundreds of individuals over hundreds of years. In contrast, the rcontroll package relies on a few functions in R to generate and provide inputs, prepare and run the simulations, and analyze the simulations through tables, figures, and maps that are easily connected to the rest of the R package ecosystem. The whole workflow can even be run for one or several simulations using a unique function (functions troll and stack). Pre-simulations functions include global parameters definition (function generate_parameters) and species and weather data input, with default values for French Guiana included in the package. Simulations are run alone (function troll) or as a stack (function stack) and stocked in three defined classes depending on the level of outputs wanted:  trollsimfull for a full set of outputs, trollsimreduced for a reduced set of outputs, and trollsimabc for outputs later used in approximate bayesian computing or other calibration methods. The post-simulation outputs are stored in the corresponding objects and can be accessed using object attributes (with @ in R) in the form of simple R objects, mainly data frames, or summarized and plotted with the print, summary and autoplot methods. Simulations can be saved using a user-defined path when run and later loaded as a simple simulation (function load_output) or a stack of simulations (function load_stack).

**Add here the Figure 2 that shows rcontroll workflow.**

# Examples

## Calibration of the TROLL model in French Guiana

gsalzet can you suggest a detailed plan here?

**Add here the figure 3 that shows calibration methods (2A) and results (2B).**

## Replication of the virtual experiment by @Schmitt2019

1. Quick introduction to the main results from @Schmitt2019.
1. Simple reproduction with rcontroll default data as Rmarkdown included in SI.
1. Quickly describe how much we find back the main result (Fig. 4?).

# Discussion

1. Take home: We developed rcontroll, an easy-to-use R package to open up the TROLL forest simulator to a wider community of ecologists and students using R.
1. Demonstrated flexibility with examples
1. Synergy with R ecosystem: tidyverse, Entropart, Maria, hetGP, calibration pacakges, sensitivity…
1. TROLL limits and future directions
    * intraspecific variability
    * water module
    * other points to be discussed with Jérôme, Isabelle & Fabian
1. rcontroll limits and future directions
    * realistic canopies with canopy constructor
    * increased user-friendliness thanks to a global user interface in shiny
    * increased interoperability with formatting function toward other tools
1. Access
    * free and open source (version 0.1.0 with GPL v3 license)
    * CRAN repository 
    * Open contribution: Github repository
    
# Acknowledgements

We thank the **WHO** for a PhD grant to G. Salzet.

# Authors’ contributions

SS and GZ conceived the ideas, SS led the package development, FF adapted TROLL for the pacakge, GZ and SS designed the example, and analysed model outputs, and SS led the writing of the manuscript. All authors contributed critically to the drafts and gave final approval for publication.

# Data Accessibility

# References
