---
title: "Lidar module"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Lidar module}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.height = 6,
  fig.width = 6
)
```

This vignette gives a quick example of a simple workflow to produce discrete lidar LAS and full waveform GEDI lidar from TROLL simulation.

# Setup

We will use `rcontroll`.

```{r libs}
suppressMessages(library(dplyr))
library(tidyr)
library(ggplot2)
suppressMessages(library(rcontroll))
library(lidR)
library(plot3D)
library(terra)
library(sf)
library(rGEDI)
```

# Lidar simulation

```{r}

sim <- troll(name = "test",path = getwd(),
             global = generate_parameters(cols = 100, rows = 100,
                                          iterperyear = 12, nbiter = 12*600),
             species = TROLLv3_species,
             climate = TROLLv3_climatedaytime12,
             daily = TROLLv3_daytimevar,lidar = generate_lidar(mean_beam_pc = 10,
                                                               sd_beam_pc = 5,
                                                               klaser_pc = 0.63,
                                                               transmittance_laser = 0.1,
                                                               iter_pointcloud_generation = 12*600-1),
             verbose = FALSE)

# information to read in file

dir_current = sim@path

```

```{r}
# read files
file_pointcloud = file.path(dir_current,"test_0.las")

# read in file
pointcloud = readLAS(file_pointcloud)
pointcloud@header # check format
pointcloud@data   # check format

# plot
plot(pointcloud)

# rGEDI needs the las files reexported temporarily (maybe to update format)
file_pointcloud_lidR = file.path(dir_current,"processing_waveforms","test_0.las")
dir.create(file.path(dir_current,"processing_waveforms"))

writeLAS(pointcloud, file_pointcloud_lidR)

# rGEDI is not on CRAN anymore, github installation did not work for me, but it worked with a download of the last available CRAN version (https://cran.r-project.org/src/contrib/Archive/rGEDI/)
# install.packages(pkgs="~/Downloads/rGEDI_0.1.11.tar.gz", type="source", repos=NULL) # worked
# library(devtools)
# devtools::install_git("https://github.com/carlos-alberto-silva/rGEDI", dependencies = TRUE) # did not work


# now generate GEDI footprint
# cf. https://github.com/carlos-alberto-silva/rGEDI
# Extracting plot center geolocations

file_pointcloud_lidR = file.path(dir_current,"processing_waveforms","test_0.las")

pointcloud = readLAS(file_pointcloud_lidR)

# we calculate waveform for a specific point within the simulated extent
wv_x_pointcloud = 50
wv_y_pointcloud = 50

# remove files, as gediWFSimulator does not overwrite
if(file.exists(file.path(dir_current,"processing_waveforms","gediWF_simulation.h5"))) file.remove(file.path(dir_current,"processing_waveforms","gediWF_simulation.h5"))

wf_pointcloud = gediWFSimulator(input = file_pointcloud_lidR, output = file.path(dir_current,"processing_waveforms","gediWF_simulation.h5"), coords = c(wv_x_pointcloud, wv_y_pointcloud))

waveform_extent = st_point(x = c(wv_x_pointcloud, wv_y_pointcloud), dim = "XYZ") |> 
  st_buffer(dist = 12.5)# bit awkward, using terra, then sf
pointcloud_clipped = clip_roi(pointcloud, waveform_extent)

par(mfrow=c(1,2), mar=c(4,4,1,1), oma=c(1,1,1,1),cex.axis = 1.2)
scatter3D(pointcloud_clipped@data$X,pointcloud_clipped@data$Y,pointcloud_clipped@data$Z,pch = 16,colkey = FALSE, main="ALS simulation (realistic extinction)",
          cex = 0.5,bty = "u",col.panel ="gray90",phi = 30,alpha=1,theta=45,
          col.grid = "gray50", xlab="UTM Easting (m)", ylab="UTM Northing (m)", zlab="Elevation (m)")

plot(wf_pointcloud, relative=TRUE, polygon=TRUE, type="l", lwd=2, col="forestgreen",
     xlab="", ylab="Elevation (m)", ylim=c(0,70))

```


```{r}
library(tidyverse)

test_0_LAI3D<- read.delim(paste0(dir_current,"/test_0_LAI.txt"))

LAI_WF <- test_0_LAI3D |>  mutate(LAD = LAI3D - lead(LAI3D)) |>  
  filter(LAD>0 | h==0) |> mutate(Intensity = if_else(h==0, 
                                                     exp(-0.2*LAI3D - ((row - 50)^2 + (col - 50)^2)/( 2 * 5.5^2))/2.5,
                                                     exp(-0.2*LAI3D - ((row - 50)^2 + (col - 50)^2)/( 2 * 5.5^2)))) |> 
  group_by(h) |>  summarize(I = sum(Intensity)) |> ungroup() |>  mutate(I = I/sum(I))

LAI_WF_sample <- sample(LAI_WF$h,size = 100000, prob = LAI_WF$I,replace = TRUE) |> density(kernel = "gaussian")



ggplot() + geom_line(data = tibble(h = LAI_WF_sample$x,WF = LAI_WF_sample$y),aes(x = h, y=WF)) + 
  geom_line(data = LAI_WF,aes(x = h, y = I/sum(I)), col = "red") + 
  coord_flip() + theme_bw()


```
