---
title: "Reproducible example"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{A simple workflow}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.height = 6,
  fig.width = 6
)
```


```{r}
library(rcontroll)
data("TROLLv3_species")
data("TROLLv3_climatedaytime12")
data("TROLLv3_daytimevar")
```

```{r}
sim1 <- troll(name = "test1",
             global = generate_parameters(cols = 100, rows = 100,
                                          iterperyear = 12, nbiter = 12*1),
             species = TROLLv3_species,
             climate = TROLLv3_climatedaytime12,
             daily = TROLLv3_daytimevar)
```

```{r}
sim2 <- troll(name = "test2",
             global = generate_parameters(cols = 100, rows = 100,
                                          iterperyear = 12, nbiter = 12*1),
             species = TROLLv3_species,
             climate = TROLLv3_climatedaytime12,
             daily = TROLLv3_daytimevar)
```
