# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title TROLL C++
#' 
#' @description
#' TROLL C++.
#' 
#' @name trollCpp
#' 
#' @param global_file std::string. global parameters file.
#' @param climate_file std::string. climate file.
#' @param species_file std::string. species file.
#' @param day_file std::string. daytime file.
#' @param forest_file std::string. forest file.
#' @param output_file std::string. output folder.
#' 
#' @return int.
#' 
#' @examples
#' \dontrun{
#' trollCpp(global_file = "test/test_input_global.txt", 
#'          climate_file = "test/test_input_climate.txt",
#'          species_file = "test/test_input_species.txt", 
#'          day_file = "test/test_input_daily.txt", 
#'          forest_file = "NULL", 
#'          output_file = "test")
#' }
#' 
#' @export
trollCpp <- function(global_file, climate_file, species_file, day_file, forest_file, output_file) {
    invisible(.Call(`_rcontroll_trollCpp`, global_file, climate_file, species_file, day_file, forest_file, output_file))
}

